"""PhyAI pi0.5 policy execution, independent of a particular robot.

The adapter supplies preprocessed tensors; the policy owns the engine and a
seeded CPU noise stream. Keeping engine setup here leaves deployment entry
points responsible only for composing a robot, an adapter, and a control loop.
"""

from __future__ import annotations

from typing import Any
from pathlib import Path
from threading import Lock, Event
from dataclasses import dataclass

from omegaconf import MISSING

from .configuration import repository_path


@dataclass
class Pi05PolicyConfig:
    """Local pi0.5 checkpoint and PhyAI engine settings, independent of a robot."""

    checkpoint: str = MISSING
    kernel_policy: str = "examples/deployment/configs/pi05_bf16.yaml"
    seed: int = 42
    use_cuda_graph: bool = True
    num_threads: int = 16

    def validate(self) -> None:
        """Check local paths and engine arguments without allocating GPU resources."""
        if self.num_threads < 1:
            raise ValueError("policy.num_threads must be positive")
        if not 0 <= self.seed < 2**64:
            raise ValueError("policy.seed must be in [0, 2**64)")
        if not self.checkpoint.strip() or not repository_path(self.checkpoint).is_dir():
            raise ValueError(
                "policy.checkpoint must name an existing checkpoint directory"
            )
        if (
            not self.kernel_policy.strip()
            or not repository_path(self.kernel_policy).is_file()
        ):
            raise ValueError(
                "policy.kernel_policy must name an existing kernel YAML file"
            )


@dataclass(frozen=True)
class Pi05PolicyRequest:
    """One preprocessed snapshot; diffusion noise is generated by the policy."""

    processed: Any


class Pi05Policy:
    """Own a BF16 PhyAI engine and a reproducible stream of diffusion noise."""

    def __init__(
        self,
        checkpoint: Path,
        *,
        kernel_policy: Path,
        seed: int = 42,
        use_cuda_graph: bool = True,
        num_threads: int = 16,
    ) -> None:
        import torch
        from phyai.utils import load_config
        from phyai.engine_config import DeviceConfig, EngineConfig, RuntimeConfig
        from phyai.kernel.config import KernelConfig
        from phyai.models.pi05.main_pi05 import PI05Args
        from phyai.models.pi05.scheduler_pi05 import PI05Request
        from phyai.models.pi05.configuration_pi05 import PI05Config

        from phyai import Engine, EngineArgs

        config = load_config(checkpoint, PI05Config)
        self._torch = torch
        self._request_type = PI05Request
        self._chunk_size = int(config.chunk_size)
        self._max_action_dim = int(config.max_action_dim)
        self._generator = torch.Generator().manual_seed(seed)
        # Keep the selected BF16 kernels and graph capture explicit. The model's
        # denoising-step count and padded action dimensions come from its config.
        self._engine = Engine(
            EngineArgs(
                plugin="pi05",
                plugin_args=PI05Args(checkpoint_dir=checkpoint, max_batch_size=1),
                config=EngineConfig(
                    device=DeviceConfig(target="cuda", params_dtype=torch.bfloat16),
                    runtime=RuntimeConfig(
                        use_cuda_graph=use_cuda_graph, num_threads=num_threads
                    ),
                    kernel=KernelConfig(config_path=str(kernel_policy)),
                ),
            )
        )
        self._lock = Lock()
        self._close_requested = Event()
        self._closed = False

    def predict(self, request: Pi05PolicyRequest) -> Any:
        """Run one synchronous prediction; RobotDeployment owns the worker loop."""
        with self._lock:
            if self._close_requested.is_set():
                raise RuntimeError("Pi05Policy is closed")
            try:
                noise = self._torch.randn(
                    1,
                    self._chunk_size,
                    self._max_action_dim,
                    generator=self._generator,
                    dtype=self._torch.float32,
                )
                processed = request.processed
                with self._torch.inference_mode():
                    # Detach output from any reusable CUDA-graph buffers before
                    # returning it to adapter postprocessing.
                    return (
                        self._engine.step(
                            self._request_type(
                                pixel_values=processed.pixel_values,
                                input_ids=processed.input_ids,
                                lang_lens=processed.lang_lens,
                                noise=noise,
                            )
                        )
                        .detach()
                        .float()
                        .cpu()
                    )
            finally:
                if self._close_requested.is_set():
                    self._close_engine()

    def _close_engine(self) -> None:
        if not self._closed:
            self._engine.close()
            self._closed = True

    def close(self) -> None:
        """Do not destroy CUDA resources underneath a timed-out predictor.

        Hardware is stopped before this call. If inference is still active,
        the worker releases its own engine in predict's finally block.
        """
        self._close_requested.set()
        if self._lock.acquire(blocking=False):
            try:
                self._close_engine()
            finally:
                self._lock.release()
